### ISSUE TITLE
Don't use snapshot

### ISSUE THREAD

**Issue by GrandSchtroumpf** [ioaNikas/Dappsnation-app#1]
[Here](https://github.com/ioaNikas/Dappsnation-app/blob/7ecf8b109f438f2406457b9e18c08dcc120d241f/src/app/views/game-details/game-details.component.ts#L22) don't use `snapshot`, use observable instead.

**Comment by GrandSchtroumpf** [comment]
Like that : 
```typescript
ngOnInit() {
    const game$ = routes.params.pipe(
      map(params => params['title']),
      map(id => this.videogameService.getVideogame(id))
    );
}
```
Et dans le html tu pipes ta valeur `game$` avec `async`. Par exemple :
```html
<section *ngIf="(game$ | async) as game">
 <h1>{{ game.title }}</h1>
</section>
```

**Comment by ioaNikas** [comment]
Merci pour ta sagesse Grand Schtroumpf.

J'ai une erreur sur les map qui ne sont pas reconnus. J'ai ne nez dans la doc pour trouver une solution.

**Comment by ioaNikas** [comment]
Est-ce que 
```Typescript
ngOnInit() {
    this.route.paramMap.subscribe(params => {
      this._title = params.get('title');
      this.videogame = this.videogameService.getVideogame(this._title);
    })
}
```

fait aussi l'affaire ?

J'essaye de tester ça avec une fonction getNextGame() qui, si j'ai bien compris, ne peut fonctionner qu'avec une observable?

**Comment by ioaNikas** [comment]
Ok problem solved grâce à tes conseils d'hier soir et des tutos firebase https://angularfirebase.com/lessons/basics-angular-router/.
Merci !
